#!/usr/bin/env bash
#
# Checks that the four places carrying the flutter_rust_bridge version agree.
#
# The generated Rust glue asserts at startup that the codegen version equals the
# runtime version, and a mismatch is a runtime crash with a confusing message. This
# script turns that into a build-time failure by comparing:
#
#   1. pubspec.yaml              (the Dart runtime)
#   2. rust/Cargo.toml           (the Rust runtime)
#   3. the installed codegen binary
#   4. lib/src/rust/frb_generated.dart  (what was actually generated)
#
# Usage:
#   scripts/check_bridge_versions.sh          # exit 1 on any mismatch
#   scripts/check_bridge_versions.sh --print  # just print what was found

set -euo pipefail

print_only=false
if [[ "${1:-}" == "--print" ]]; then
  print_only=true
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# macOS ships bash 3.2, which has no associative arrays and no `mapfile`. Plain
# variables only, so this script runs under /bin/sh-ish bash as well as bash 5.
failures=0

# Reports one version.
record() {
  local label="$1" version="$2"
  printf '  %-28s %s\n' "$label" "$version"
}

echo "flutter_rust_bridge versions"

pubspec_version="$(grep -m1 -E '^  flutter_rust_bridge:' pubspec.yaml | sed -E 's/.*flutter_rust_bridge:[[:space:]]*//' | tr -d '"' || true)"
record "pubspec.yaml" "${pubspec_version:-NOT FOUND}"

cargo_version="$(grep -m1 -E '^flutter_rust_bridge[[:space:]]*=' rust/Cargo.toml | sed -E 's/.*=[[:space:]]*"=?([^"]+)".*/\1/' || true)"
record "rust/Cargo.toml" "${cargo_version:-NOT FOUND}"

if command -v flutter_rust_bridge_codegen >/dev/null 2>&1; then
  codegen_version="$(flutter_rust_bridge_codegen --version | awk '{print $2}')"
else
  codegen_version="NOT INSTALLED"
fi
record "codegen binary" "$codegen_version"

generated_file="lib/src/rust/frb_generated.dart"
generated_version="$(grep -m1 -oE "codegenVersion => '[^']+'" "$generated_file" 2>/dev/null | sed -E "s/.*'([^']+)'.*/\1/" || true)"
record "generated Dart" "${generated_version:-NOT RUN YET}"

if $print_only; then
  exit 0
fi

# The runtime versions must match exactly: the glue compares them at startup.
if [[ "$pubspec_version" != "$cargo_version" ]]; then
  echo
  echo "MISMATCH: pubspec.yaml has $pubspec_version, rust/Cargo.toml has $cargo_version." >&2
  echo "  Move both to the same version and run 'just bridge-versions' again." >&2
  failures=$((failures + 1))
fi

if [[ "$codegen_version" != "$pubspec_version" ]]; then
  echo
  echo "MISMATCH: the codegen binary is $codegen_version but the Dart runtime is $pubspec_version." >&2
  echo "  Install the matching generator: cargo install flutter_rust_bridge_codegen --version $pubspec_version --locked" >&2
  failures=$((failures + 1))
fi

# A stale generated file is not fatal — it just means `just gen` is due — but a file
# generated by a *different* version would crash at startup, so that is fatal.
if [[ "$generated_version" != "$pubspec_version" && "$generated_version" != "NOT RUN YET" ]]; then
  echo
  echo "MISMATCH: $generated_file was generated by $generated_version, runtime is $pubspec_version." >&2
  echo "  Run 'just gen' to regenerate it." >&2
  failures=$((failures + 1))
fi

echo
if ((failures > 0)); then
  echo "$failures version mismatch(es) found." >&2
  exit 1
fi

echo "All four agree on $pubspec_version."
