#!/usr/bin/env bash
#
# 检查承载 flutter_rust_bridge 版本的四处是否一致。
#
# 生成的 Rust 胶水代码会在启动时断言 codegen 版本等于运行时版本，不一致就是
# 一次带着令人困惑信息的运行时崩溃。这个脚本通过比较下面几处，把它变成
# 构建期的失败：
#
#   1. pubspec.yaml              （Dart 运行时）
#   2. rust/Cargo.toml           （Rust 运行时）
#   3. 已安装的 codegen 二进制
#   4. lib/src/rust/frb_generated.dart  （实际生成出来的内容）
#
# 用法：
#   scripts/check_bridge_versions.sh          # 任何不一致都以退出码 1 结束
#   scripts/check_bridge_versions.sh --print  # 只打印找到的内容

set -euo pipefail

print_only=false
if [[ "${1:-}" == "--print" ]]; then
  print_only=true
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# macOS 自带 bash 3.2，它没有关联数组，也没有 `mapfile`。这里只用普通变量，
# 这样脚本既能跑在类 /bin/sh 的 bash 下，也能跑在 bash 5 下。
failures=0

# 记录一个版本。
record() {
  local label="$1" version="$2"
  printf '  %-28s %s\n' "$label" "$version"
}

echo "flutter_rust_bridge versions"

pubspec_version="$(grep -m1 -E '^  flutter_rust_bridge:' pubspec.yaml | sed -E 's/.*flutter_rust_bridge:[[:space:]]*//' | tr -d '"' || true)"
record "pubspec.yaml" "${pubspec_version:-NOT FOUND}"

cargo_version="$(grep -m1 -E '^flutter_rust_bridge[[:space:]]*=' rust/Cargo.toml | sed -E 's/.*=[[:space:]]*"=?([^"]+)".*/\1/' || true)"
record "rust/Cargo.toml" "${cargo_version:-NOT FOUND}"

if command -v flutter_rust_bridge_codegen >/dev/null 2>&1; then
  codegen_version="$(flutter_rust_bridge_codegen --version | awk '{print $2}')"
else
  codegen_version="NOT INSTALLED"
fi
record "codegen binary" "$codegen_version"

generated_file="lib/src/rust/frb_generated.dart"
generated_version="$(grep -m1 -oE "codegenVersion => '[^']+'" "$generated_file" 2>/dev/null | sed -E "s/.*'([^']+)'.*/\1/" || true)"
record "generated Dart" "${generated_version:-NOT RUN YET}"

if $print_only; then
  exit 0
fi

# 运行时版本必须完全一致：胶水代码会在启动时比较它们。
if [[ "$pubspec_version" != "$cargo_version" ]]; then
  echo
  echo "MISMATCH: pubspec.yaml has $pubspec_version, rust/Cargo.toml has $cargo_version." >&2
  echo "  Move both to the same version and run 'just bridge-versions' again." >&2
  failures=$((failures + 1))
fi

if [[ "$codegen_version" != "$pubspec_version" ]]; then
  echo
  echo "MISMATCH: the codegen binary is $codegen_version but the Dart runtime is $pubspec_version." >&2
  echo "  Install the matching generator: cargo install flutter_rust_bridge_codegen --version $pubspec_version --locked" >&2
  failures=$((failures + 1))
fi

# 生成文件过期并不致命——它只意味着该跑 `just gen` 了——但由*不同*版本生成的
# 文件会在启动时崩溃，所以那种情况是致命的。
if [[ "$generated_version" != "$pubspec_version" && "$generated_version" != "NOT RUN YET" ]]; then
  echo
  echo "MISMATCH: $generated_file was generated by $generated_version, runtime is $pubspec_version." >&2
  echo "  Run 'just gen' to regenerate it." >&2
  failures=$((failures + 1))
fi

echo
if ((failures > 0)); then
  echo "$failures version mismatch(es) found." >&2
  exit 1
fi

echo "All four agree on $pubspec_version."
