// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fibonacci_blocking`, `run_blocking`

/// Greets `name` after waiting `delay_ms` milliseconds.
///
/// Dart signature: `Future<String> delayedHello({required String name, required
/// int delayMs})`. Values above [`MAX_DELAY_MS`] are clamped instead of rejected,
/// which keeps a slider in the UI from turning into an error dialog.
///
/// # Errors
///
/// Cannot fail today. The `Result` is part of the scaffold on purpose: replacing
/// the sleep with a real network call will not change the Dart signature.
Future<String> delayedHello({required String name, required int delayMs}) =>
    RustLib.instance.api.crateApiAsyncDemoDelayedHello(
      name: name,
      delayMs: delayMs,
    );

/// The `n`-th Fibonacci number, with `F(0) = 0` and `F(1) = 1`.
///
/// Stands in for any CPU-bound computation: the arithmetic runs on a blocking
/// thread, so N calls in parallel use N threads of the pool instead of queueing
/// behind each other on the async runtime.
///
/// # Errors
///
/// Returns an error for `n > `[`MAX_FIBONACCI_N`], where the result would not fit
/// in a `u64`.
Future<BigInt> fibonacci({required int n}) =>
    RustLib.instance.api.crateApiAsyncDemoFibonacci(n: n);
