// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`

/// The smallest possible bridge call.
///
/// `#[frb(sync)]` makes this a plain synchronous `String` in Dart instead of a
/// `Future<String>`: the call runs on the calling isolate, so it must stay cheap.
/// A `format!` qualifies; a file read does not — see [`crate::api::async_demo`].
String hello({required String name}) =>
    RustLib.instance.api.crateApiHelloHello(name: name);

/// Validates `name` and renders it in `style`, asynchronously.
///
/// Dart signature: `Future<Greeting> greet({required String name, required
/// GreetingStyle style})`.
///
/// # Errors
///
/// Surfaces [`rust_flutter_core::CoreError::InvalidInput`] to Dart as an
/// `AnyhowException` when the name is blank or longer than
/// [`rust_flutter_core::domain::MAX_RECIPIENT_LEN`] characters. The `?` below is
/// the whole translation layer: `CoreError` implements `std::error::Error`, so
/// `anyhow` picks it up with its `Display` message intact.
Future<Greeting> greet({required String name, required GreetingStyle style}) =>
    RustLib.instance.api.crateApiHelloGreet(name: name, style: style);

/// A greeting rendered by Rust and handed to Dart as a plain data class.
///
/// Public fields, no invariants to preserve on the Dart side: the domain already
/// validated the data, so `recipient` is trimmed and `message` matches `style`.
class Greeting {
  /// The validated, trimmed name the greeting addresses.
  final String recipient;

  /// The rendered sentence.
  final String message;

  /// The tone `message` was rendered in.
  final GreetingStyle style;

  const Greeting({
    required this.recipient,
    required this.message,
    required this.style,
  });

  @override
  int get hashCode => recipient.hashCode ^ message.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Greeting &&
          runtimeType == other.runtimeType &&
          recipient == other.recipient &&
          message == other.message &&
          style == other.style;
}

/// Tone used when composing a greeting.
///
/// Mirrors [`rust_flutter_core::domain::GreetingStyle`]; the `From` impls below
/// keep the two in step.
///
/// Note what is *not* derived: `Default`. flutter_rust_bridge bridges every
/// derivable trait it recognises as an extra Dart entry point, so a needless
/// `#[derive(Default)]` here would add a `GreetingStyle.default_()` to the
/// generated API that nothing calls.
enum GreetingStyle {
  /// `Hello, Ada!`
  plain,

  /// `Hey Ada, great to see you!`
  enthusiastic,

  /// `Good day, Ada.`
  formal,
}
