// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`

/// Operating system this native library was compiled for.
///
/// Unlike `Platform.operatingSystem` in Dart, this reports the target the *Rust*
/// half was built for. The two agree in a correctly built app, and comparing them
/// is a quick way to spot a stale native library.
String platformName() => RustLib.instance.api.crateApiPlatformPlatformName();

/// Coarse group [`platform_name`] belongs to.
PlatformFamily platformFamily() =>
    RustLib.instance.api.crateApiPlatformPlatformFamily();

/// Whether the app runs on Linux, macOS or Windows.
bool isDesktop() => RustLib.instance.api.crateApiPlatformIsDesktop();

/// Best-effort application data directory for `app_id`.
///
/// `None` means "this crate has no answer for the platform" — iOS and the web
/// build, most notably. Prefer `path_provider` on the Dart side when the app needs
/// a sandbox-correct, writable directory; this is a dependency-free hint.
String? defaultDataDir({required String appId}) =>
    RustLib.instance.api.crateApiPlatformDefaultDataDir(appId: appId);

/// Reads the host once and returns everything at the same time.
///
/// [`app_id`](Self::data_dir) is used to namespace the data directory, usually
/// with the application id (`com.example.frs_kit`).
PlatformSummary platformSummary({required String appId}) =>
    RustLib.instance.api.crateApiPlatformPlatformSummary(appId: appId);

/// Coarse grouping of operating systems, mirroring
/// [`rust_flutter_platform::PlatformFamily`].
enum PlatformFamily {
  /// Linux, macOS and Windows.
  desktop,

  /// Android and iOS.
  mobile,

  /// Anything else, including the web build and BSDs.
  other,
}

/// Everything the UI wants to know about the host, in one call.
class PlatformSummary {
  /// Operating system this native library was compiled for, e.g. `"macos"`.
  final String name;

  /// Coarse group `name` belongs to.
  final PlatformFamily family;

  /// Whether the app runs on a desktop OS.
  final bool isDesktop;

  /// Best-effort per-user data directory, or `None` when this crate has no
  /// answer for the platform.
  final String? dataDir;

  const PlatformSummary({
    required this.name,
    required this.family,
    required this.isDesktop,
    this.dataDir,
  });

  @override
  int get hashCode =>
      name.hashCode ^ family.hashCode ^ isDesktop.hashCode ^ dataDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          family == other.family &&
          isDesktop == other.isDesktop &&
          dataDir == other.dataDir;
}
