// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Counts down from `count` to `1`, one value per `interval_ms`, then closes.
///
/// Dart signature: `Stream<int> countdown({required int count, required int
/// intervalMs})`. Values above [`MAX_INTERVAL_MS`] are clamped, so a UI slider
/// cannot make the stream crawl for minutes.
///
/// Returning `Ok(())` closes the stream normally. To fail it instead, send
/// `sink.add_error(...)` and still return `Ok(())`, or return `Err(...)` — either
/// way Dart sees an error event rather than a silent stop.
///
/// # Cancellation
///
/// When Dart cancels the subscription (a disposed widget, a rebuilt `FutureBuilder`
/// with a new key), the next `add` fails. Breaking out of the loop on that failure
/// is what keeps a cancelled `Stream` from holding a worker thread until it would
/// have finished on its own.
Stream<int> countdown({required int count, required int intervalMs}) => RustLib
    .instance
    .api
    .crateApiStreamDemoCountdown(count: count, intervalMs: intervalMs);
