// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clamp_interval`

/// 从 `count` 倒数到 `1`，每 `interval_ms` 发一个值，然后关闭。
///
/// Dart 签名：`Stream<int> countdown({required int count, required int
/// intervalMs})`。超过 [`MAX_INTERVAL_MS`] 的值会被 clamp，所以 UI 滑块无法让
/// 这个流慢到几分钟才发一次。
///
/// 返回 `Ok(())` 会正常关闭流。要让它失败，可以发 `sink.add_error(...)` 之后
/// 仍然返回 `Ok(())`，或者直接返回 `Err(...)` —— 两种方式 Dart 看到的都是错误
/// 事件，而不是静默停止。
///
/// # 取消
///
/// 当 Dart 取消订阅（widget 被 dispose、带新 key 的 `FutureBuilder` 重建）后，
/// 下一次 `add` 会失败。在这个失败上跳出循环，才能让已取消的 `Stream` 不再占着
/// worker 线程直到它自己跑完。
Stream<int> countdown({required int count, required int intervalMs}) => RustLib
    .instance
    .api
    .crateApiStreamDemoCountdown(count: count, intervalMs: intervalMs);
